import type { HabitCategory, TodayHabit, WeeklyGoal } from "../../domain/habits/models";

export const demoCategories: readonly HabitCategory[] = [
  { id: "health", name: "Health", icon: "heart-pulse", sortOrder: 0 },
  { id: "learning", name: "Learning", icon: "book-open", sortOrder: 1 },
  { id: "productivity", name: "Productivity", icon: "briefcase-business", sortOrder: 2 },
  { id: "personal", name: "Personal", icon: "user-round", sortOrder: 3 },
];

export const demoTodayHabits: readonly TodayHabit[] = [
  {
    id: "movement",
    name: "Morning movement",
    description: "A short walk or mobility session",
    type: "duration",
    status: "completed",
    timeOfDay: "morning",
    streak: 12,
    value: 20,
    targetValue: 20,
    targetUnit: "min",
    categoryId: "health",
    categoryName: "Health",
    icon: "activity",
    colour: "#73bd8c",
  },
  {
    id: "make-bed",
    name: "Make the bed",
    type: "binary",
    status: "completed",
    timeOfDay: "morning",
    streak: 31,
    categoryId: "personal",
    categoryName: "Personal",
    icon: "check",
    colour: "#9c7bd8",
  },
  {
    id: "read",
    name: "Read",
    type: "quantity",
    status: "incomplete",
    timeOfDay: "morning",
    streak: 4,
    value: 12,
    targetValue: 20,
    targetUnit: "pages",
    categoryId: "learning",
    categoryName: "Learning",
    icon: "book",
    colour: "#62a5d8",
  },
  {
    id: "deep-work",
    name: "Deep work",
    description: "One focused block without notifications",
    type: "duration",
    status: "completed",
    timeOfDay: "afternoon",
    streak: 6,
    value: 90,
    targetValue: 90,
    targetUnit: "min",
    categoryId: "productivity",
    categoryName: "Productivity",
    icon: "sparkles",
    colour: "#d99a63",
  },
  {
    id: "water",
    name: "Drink water",
    type: "quantity",
    status: "incomplete",
    timeOfDay: "afternoon",
    streak: 8,
    value: 1.4,
    targetValue: 2,
    targetUnit: "L",
    categoryId: "health",
    categoryName: "Health",
    icon: "droplet",
    colour: "#62a5d8",
  },
  {
    id: "journal",
    name: "Journal",
    type: "binary",
    status: "completed",
    timeOfDay: "evening",
    streak: 9,
    categoryId: "personal",
    categoryName: "Personal",
    icon: "book",
    colour: "#9c7bd8",
  },
  {
    id: "meditate",
    name: "Meditate",
    type: "duration",
    status: "incomplete",
    timeOfDay: "evening",
    streak: 3,
    value: 0,
    targetValue: 10,
    targetUnit: "min",
    categoryId: "health",
    categoryName: "Health",
    icon: "heart",
    colour: "#73bd8c",
  },
  {
    id: "tomorrow",
    name: "Plan tomorrow",
    type: "binary",
    status: "completed",
    timeOfDay: "evening",
    streak: 14,
    categoryId: "productivity",
    categoryName: "Productivity",
    icon: "check",
    colour: "#d99a63",
  },
];

export const demoWeeklyGoals: readonly WeeklyGoal[] = [
  { id: "exercise", name: "Exercise", completed: 3, target: 4, unit: "sessions" },
  { id: "reading", name: "Reading", completed: 72, target: 100, unit: "pages" },
  { id: "meditation", name: "Meditation", completed: 4, target: 7, unit: "days" },
];
